apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/tcp-probe: 'true'
    prometheus.io/tcp-probe-port: '8000'
#    prometheus.io/app-metrics: 'true'
#    prometheus.io/app-metrics-port: '8000'
#    prometheus.io/app-metrics-path: '/aaa.json'
#    prometheus.io/app-info-env: 'dafault'
#    prometheus.io/app-info-name: 'nginx-ggk'
    prometheus.io/http-probe: 'true'
    prometheus.io/http-probe-port: '8000'
    prometheus.io/http-probe-path: '/aaa.json'
spec:
  ports: 
    - port: 8000
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    name: nginx
