apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
  - name: redis-exporter
    port: 9121
    targetPort: 9121
    nodePort: 39121
    protocol: TCP
